version: 2.1

orbs:
  salesforce-sfdx: circleci/salesforce-sfdx@2.2.0

jobs:
  check-deploy:
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
      - run: ls -la

workflows:
  basic-test:
    jobs:
      - check-deploy
