version: 2.1

orbs:
  sfdx: circleci/salesforce-sfdx@2.2.0

jobs:
  check-deploy:
    executor: sfdx/default
    steps:
      - checkout
      - sfdx/install
      - run:
          name: install test status plugin
          command: |
            echo 'sfdx plugins:install deploy-test-status'
            echo y | sfdx plugins:install deploy-test-status
            sfdx plugins

workflows:
  basic-test:
    jobs:
      - check-deploy
