name: CI

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Navigate to checked out folder
        run: cd $GITHUB_WORKSPACE

      - name: Cache sfdx
        uses: actions/cache@v2
        env:
          cache-name: cache-sfdx
        with:
          # sfdx-actions/setup-sfdx@v1 installs all into ./sfdx folder
          path: ./sfdx
          key: sfdx-cache

      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.TEST_SANDBOX }}
        if: $(ls sfdx | wc -l) -eq "0"

      - name: install test status plugin
        run: |
          echo 'sfdx plugins:install deploy-test-status'
          echo y | sfdx plugins:install deploy-test-status
          sfdx plugins
        if: $(ls sfdx | wc -l) -eq "0"

      - name: Validate Changes
        run: |
          sfdx force:source:deploy -p soql-criteria-builder -c -l RunSpecifiedTests \
          -r tmo_soqlCriteriaBuilderTest,tmo_soqlCriteriaBuilderDemoTest
          sfdx force:source:deploy:report --json > deploy-report.json

      - name: Test Status
        run: |
          mkdir -p test-results/junit
          JOB_ID=$(jq .result.id deploy-report.json -r)
          echo $JOB_ID
          sfdx tmo:deploy:test:status -i $JOB_ID > test-results/junit/report.xml

      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        with:
          report_paths: "test-results/junit/report.xml"
